# Generated by Django 2.0.1 on 2019-02-10 14:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('chatting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('city', models.CharField(default='', max_length=300)),
                ('contacts', models.ManyToManyField(blank=True, default=[], related_name='athlete_contact', to=settings.AUTH_USER_MODEL)),
                ('discussions', models.ManyToManyField(blank=True, default=[], related_name='athlete_discussion', to='chatting.Discussion')),
                ('status', models.ManyToManyField(blank=True, default=[], related_name='athlete_status', to='publication.Status')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, related_name='athlete_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('city', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default="This user doesn't put description", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('date_creation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=300)),
                ('place', models.CharField(default='', max_length=300)),
                ('contacts', models.ManyToManyField(blank=True, default=[], related_name='company_contact', to=settings.AUTH_USER_MODEL)),
                ('discussions', models.ManyToManyField(blank=True, default=[], related_name='company_discussion', to='chatting.Discussion')),
                ('employees', models.ManyToManyField(blank=True, default=[], related_name='employee_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('weblink', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(blank=True, default=[], related_name='products_company', to='profil.Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ManyToManyField(blank=True, default=[], related_name='company_status', to='publication.Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='coachings',
            field=models.ManyToManyField(blank=True, default=[], related_name='coaching_coach', to='profil.Coaching'),
        ),
        migrations.AddField(
            model_name='coach',
            name='contacts',
            field=models.ManyToManyField(blank=True, default=[], related_name='coach_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='discussions',
            field=models.ManyToManyField(blank=True, default=[], related_name='coach_discussion', to='chatting.Discussion'),
        ),
        migrations.AddField(
            model_name='coach',
            name='status',
            field=models.ManyToManyField(blank=True, default=[], related_name='coach_status', to='publication.Status'),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, related_name='coach_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
