# Generated by Django 2.0.1 on 2019-02-10 14:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_read', models.BooleanField(default=False)),
                ('for_who', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='for_who', to=settings.AUTH_USER_MODEL)),
                ('from_who', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='from_who', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='status_notification', to='publication.Status')),
            ],
        ),
        migrations.CreateModel(
            name='RequestContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_request', models.ForeignKey(blank=True, on_delete=True, related_name='from_request', to=settings.AUTH_USER_MODEL)),
                ('to_request', models.ForeignKey(blank=True, on_delete=True, related_name='to_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
