# Generated by Django 2.0.1 on 2019-02-10 14:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('members', models.ManyToManyField(blank=True, default=[], to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=True, related_name='author_message', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, on_delete=True, related_name='receiver_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='messages',
            field=models.ManyToManyField(blank=True, default=[], to='chatting.Message'),
        ),
    ]
